/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atweb_csdl;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hungh
 */
public class Home extends javax.swing.JFrame {
    
    /**
     * Creates new form Home
     */
    
    private Connection cn = ConnectDB.SQLConnect();
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    private int state_add_sv = -1, state_add_diem = -1, clicked_search_LOP = 0, clicked_search_DIEM = 0;
    
    public Home() {
        initComponents();
        jpnQllop.setVisible(true);
        jpnQlsv.setVisible(false);
        jpnQldiem.setVisible(false);
        showLopList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnMenu = new javax.swing.JPanel();
        jpn1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpn2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpn3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpnCenter = new javax.swing.JPanel();
        jpnQllop = new javax.swing.JPanel();
        jpnSearchLop = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtSearchLop = new javax.swing.JTextField();
        jtbSearchLop = new javax.swing.JToggleButton();
        jpnTableLop = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLop = new javax.swing.JTable();
        jpnUser = new javax.swing.JPanel();
        jpnQlsv = new javax.swing.JPanel();
        jpnUpdateSv = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNewMasv = new javax.swing.JTextField();
        txtNewName = new javax.swing.JTextField();
        txtNewAddress = new javax.swing.JTextField();
        txtNewMalop = new javax.swing.JTextField();
        txtNewUsn = new javax.swing.JTextField();
        txtNewPass = new javax.swing.JTextField();
        jtbSaveSv = new javax.swing.JToggleButton();
        jtbStopUpdatingSv = new javax.swing.JToggleButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jdcNewBirth = new com.toedter.calendar.JDateChooser();
        jpnTableSv = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSv = new javax.swing.JTable();
        jpnSearchSv = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtSearchLopSv = new javax.swing.JTextField();
        jtbAddSv = new javax.swing.JToggleButton();
        jtbDelSv = new javax.swing.JToggleButton();
        jtbEditSv = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtbSearchSv = new javax.swing.JToggleButton();
        jpnQldiem = new javax.swing.JPanel();
        jpnSearchDiem = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtSearchMasv = new javax.swing.JTextField();
        jtbSearchDiem = new javax.swing.JToggleButton();
        jtbAddDiem = new javax.swing.JToggleButton();
        jtbEditDiem = new javax.swing.JToggleButton();
        jtbDelDiem = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jpnTableDiem = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDiem = new javax.swing.JTable();
        jpnUpdateDiem = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cbxDsHocphan = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtDiemHocPhan = new javax.swing.JTextField();
        jtbSaveDiem = new javax.swing.JToggleButton();
        jtbStopSavingDiem = new javax.swing.JToggleButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jpnHeader.setBackground(new java.awt.Color(0, 0, 255));
        jpnHeader.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        javax.swing.GroupLayout jpnHeaderLayout = new javax.swing.GroupLayout(jpnHeader);
        jpnHeader.setLayout(jpnHeaderLayout);
        jpnHeaderLayout.setHorizontalGroup(
            jpnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHeaderLayout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(jLabel1)
                .addContainerGap(512, Short.MAX_VALUE))
        );
        jpnHeaderLayout.setVerticalGroup(
            jpnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHeaderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jpnMenu.setBackground(new java.awt.Color(255, 255, 255));

        jpn1.setBackground(new java.awt.Color(255, 255, 255));
        jpn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuMouseExit(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("QUẢN LÝ LỚP HỌC");

        javax.swing.GroupLayout jpn1Layout = new javax.swing.GroupLayout(jpn1);
        jpn1.setLayout(jpn1Layout);
        jpn1Layout.setHorizontalGroup(
            jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn1Layout.setVerticalGroup(
            jpn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jpn2.setBackground(new java.awt.Color(255, 255, 255));
        jpn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuMouseExit(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("QUẢN LÝ SINH VIÊN");

        javax.swing.GroupLayout jpn2Layout = new javax.swing.GroupLayout(jpn2);
        jpn2.setLayout(jpn2Layout);
        jpn2Layout.setHorizontalGroup(
            jpn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        jpn2Layout.setVerticalGroup(
            jpn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jpn3.setBackground(new java.awt.Color(255, 255, 255));
        jpn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuMouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuMouseExit(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("QUẢN LÝ ĐIỂM");

        javax.swing.GroupLayout jpn3Layout = new javax.swing.GroupLayout(jpn3);
        jpn3.setLayout(jpn3Layout);
        jpn3Layout.setHorizontalGroup(
            jpn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn3Layout.setVerticalGroup(
            jpn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jpn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jpn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jpn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jLabel13.setText("Tìm LỚP nhanh theo Mã Lớp hoặc Tên Lớp");

        jtbSearchLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N

        javax.swing.GroupLayout jpnSearchLopLayout = new javax.swing.GroupLayout(jpnSearchLop);
        jpnSearchLop.setLayout(jpnSearchLopLayout);
        jpnSearchLopLayout.setHorizontalGroup(
            jpnSearchLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSearchLopLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchLop, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtbSearchLop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jpnSearchLopLayout.setVerticalGroup(
            jpnSearchLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSearchLopLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpnSearchLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchLop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbSearchLop, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jTableLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ LỚP", "TÊN LỚP", "TÊN NHÂN VIÊN", "SỈ SỐ"
            }
        ));
        jScrollPane1.setViewportView(jTableLop);

        javax.swing.GroupLayout jpnTableLopLayout = new javax.swing.GroupLayout(jpnTableLop);
        jpnTableLop.setLayout(jpnTableLopLayout);
        jpnTableLopLayout.setHorizontalGroup(
            jpnTableLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1253, Short.MAX_VALUE)
        );
        jpnTableLopLayout.setVerticalGroup(
            jpnTableLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnUserLayout = new javax.swing.GroupLayout(jpnUser);
        jpnUser.setLayout(jpnUserLayout);
        jpnUserLayout.setHorizontalGroup(
            jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        jpnUserLayout.setVerticalGroup(
            jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnQllopLayout = new javax.swing.GroupLayout(jpnQllop);
        jpnQllop.setLayout(jpnQllopLayout);
        jpnQllopLayout.setHorizontalGroup(
            jpnQllopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQllopLayout.createSequentialGroup()
                .addComponent(jpnSearchLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpnTableLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnQllopLayout.setVerticalGroup(
            jpnQllopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQllopLayout.createSequentialGroup()
                .addGroup(jpnQllopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnSearchLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jpnTableLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("MASV");

        jLabel6.setText("HỌ TÊN");

        jLabel7.setText("NGÀY SINH");

        jLabel8.setText("ĐỊA CHỈ");

        jLabel9.setText("MÃ LỚP");

        jLabel10.setText("TÊN ĐĂNG NHẬP");

        jLabel11.setText("MẬT KHẨU");

        jtbSaveSv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jtbSaveSv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveNewSvMouseClick(evt);
            }
        });

        jtbStopUpdatingSv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stop.png"))); // NOI18N
        jtbStopUpdatingSv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StopSavingSv(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Lưu");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Hủy");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpnUpdateSvLayout = new javax.swing.GroupLayout(jpnUpdateSv);
        jpnUpdateSv.setLayout(jpnUpdateSvLayout);
        jpnUpdateSvLayout.setHorizontalGroup(
            jpnUpdateSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUpdateSvLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jpnUpdateSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnUpdateSvLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jpnUpdateSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtbSaveSv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jpnUpdateSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtbStopUpdatingSv, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtNewMasv, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(txtNewName)
                    .addComponent(jLabel7)
                    .addComponent(txtNewAddress)
                    .addComponent(txtNewMalop)
                    .addComponent(txtNewUsn)
                    .addComponent(txtNewPass)
                    .addComponent(jdcNewBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jpnUpdateSvLayout.setVerticalGroup(
            jpnUpdateSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUpdateSvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNewBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewMalop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewUsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jpnUpdateSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbSaveSv)
                    .addComponent(jtbStopUpdatingSv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnUpdateSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTableSv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MASV", "HỌ TÊN", "NGÀY SINH", "ĐỊA CHỈ", "TÊN LOGIN", "MẬT KHẨU"
            }
        ));
        jScrollPane2.setViewportView(jTableSv);

        javax.swing.GroupLayout jpnTableSvLayout = new javax.swing.GroupLayout(jpnTableSv);
        jpnTableSv.setLayout(jpnTableSvLayout);
        jpnTableSvLayout.setHorizontalGroup(
            jpnTableSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        jpnTableSvLayout.setVerticalGroup(
            jpnTableSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jLabel12.setText("Nhập Mã lớp hoặc Tên lớp");

        jtbAddSv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jtbAddSv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddSvMouseClick(evt);
            }
        });

        jtbDelSv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/del.png"))); // NOI18N

        jtbEditSv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Thêm");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Xóa");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Sửa");

        jtbSearchSv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jtbSearchSv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchSvMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnSearchSvLayout = new javax.swing.GroupLayout(jpnSearchSv);
        jpnSearchSv.setLayout(jpnSearchSvLayout);
        jpnSearchSvLayout.setHorizontalGroup(
            jpnSearchSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSearchSvLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchLopSv, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtbSearchSv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnSearchSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtbAddSv, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jpnSearchSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtbDelSv, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jpnSearchSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtbEditSv, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        jpnSearchSvLayout.setVerticalGroup(
            jpnSearchSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSearchSvLayout.createSequentialGroup()
                .addGroup(jpnSearchSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnSearchSvLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jpnSearchSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtbSearchSv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchLopSv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnSearchSvLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnSearchSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtbDelSv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtbEditSv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtbAddSv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnSearchSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnQlsvLayout = new javax.swing.GroupLayout(jpnQlsv);
        jpnQlsv.setLayout(jpnQlsvLayout);
        jpnQlsvLayout.setHorizontalGroup(
            jpnQlsvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQlsvLayout.createSequentialGroup()
                .addComponent(jpnTableSv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jpnUpdateSv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jpnSearchSv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnQlsvLayout.setVerticalGroup(
            jpnQlsvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQlsvLayout.createSequentialGroup()
                .addComponent(jpnSearchSv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jpnQlsvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnTableSv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnUpdateSv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jpnSearchDiem.setPreferredSize(new java.awt.Dimension(737, 103));

        jLabel14.setText("Nhập Mã sinh viên");

        jtbSearchDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jtbSearchDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchDiemMouseClick(evt);
            }
        });

        jtbAddDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jtbAddDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddDiemMouseClick(evt);
            }
        });

        jtbEditDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/del.png"))); // NOI18N

        jtbDelDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Thêm");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Sửa");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Xóa");

        javax.swing.GroupLayout jpnSearchDiemLayout = new javax.swing.GroupLayout(jpnSearchDiem);
        jpnSearchDiem.setLayout(jpnSearchDiemLayout);
        jpnSearchDiemLayout.setHorizontalGroup(
            jpnSearchDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSearchDiemLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchMasv, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtbSearchDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnSearchDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbAddDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jpnSearchDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbEditDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jpnSearchDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbDelDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        jpnSearchDiemLayout.setVerticalGroup(
            jpnSearchDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSearchDiemLayout.createSequentialGroup()
                .addGroup(jpnSearchDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnSearchDiemLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jpnSearchDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtbSearchDiem)
                            .addGroup(jpnSearchDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSearchMasv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpnSearchDiemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnSearchDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtbEditDiem)
                            .addComponent(jtbDelDiem)
                            .addComponent(jtbAddDiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnSearchDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTableDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ HỌC PHẦN", "TÊN HỌC PHẦN", "ĐIỂM"
            }
        ));
        jScrollPane3.setViewportView(jTableDiem);

        javax.swing.GroupLayout jpnTableDiemLayout = new javax.swing.GroupLayout(jpnTableDiem);
        jpnTableDiem.setLayout(jpnTableDiemLayout);
        jpnTableDiemLayout.setHorizontalGroup(
            jpnTableDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        jpnTableDiemLayout.setVerticalGroup(
            jpnTableDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel23.setText("Chọn học phần cần nhập điểm");

        cbxDsHocphan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbxDsHocphan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel24.setText("Nhập điểm");

        txtDiemHocPhan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jtbSaveDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jtbSaveDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveDiemMouseClick(evt);
            }
        });

        jtbStopSavingDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stop.png"))); // NOI18N
        jtbStopSavingDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StopSavingDiem(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Lưu");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Hủy");

        javax.swing.GroupLayout jpnUpdateDiemLayout = new javax.swing.GroupLayout(jpnUpdateDiem);
        jpnUpdateDiem.setLayout(jpnUpdateDiemLayout);
        jpnUpdateDiemLayout.setHorizontalGroup(
            jpnUpdateDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUpdateDiemLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jpnUpdateDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnUpdateDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDiemHocPhan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbxDsHocphan, javax.swing.GroupLayout.Alignment.LEADING, 0, 232, Short.MAX_VALUE))
                    .addGroup(jpnUpdateDiemLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jpnUpdateDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtbSaveDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(jpnUpdateDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtbStopSavingDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpnUpdateDiemLayout.setVerticalGroup(
            jpnUpdateDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUpdateDiemLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxDsHocphan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDiemHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jpnUpdateDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbSaveDiem)
                    .addComponent(jtbStopSavingDiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnUpdateDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnQldiemLayout = new javax.swing.GroupLayout(jpnQldiem);
        jpnQldiem.setLayout(jpnQldiemLayout);
        jpnQldiemLayout.setHorizontalGroup(
            jpnQldiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQldiemLayout.createSequentialGroup()
                .addComponent(jpnTableDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jpnUpdateDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jpnSearchDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 1253, Short.MAX_VALUE)
        );
        jpnQldiemLayout.setVerticalGroup(
            jpnQldiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQldiemLayout.createSequentialGroup()
                .addComponent(jpnSearchDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jpnQldiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnUpdateDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnTableDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpnCenterLayout = new javax.swing.GroupLayout(jpnCenter);
        jpnCenter.setLayout(jpnCenterLayout);
        jpnCenterLayout.setHorizontalGroup(
            jpnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnQllop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnQlsv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnQldiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnCenterLayout.setVerticalGroup(
            jpnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnQllop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnQlsv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnQldiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClick
        if(evt.getSource() == jpn1){
            jpnQllop.setVisible(true);
            jpnQlsv.setVisible(false);
            jpnQldiem.setVisible(false);
        }
        if(evt.getSource() == jpn2){
            jpnQllop.setVisible(false);
            jpnQlsv.setVisible(true);
            jpnQldiem.setVisible(false);
            
            state_add_sv = -1;
            jpnUpdateSv.setVisible(false);
        }
        if(evt.getSource() == jpn3){
            jpnQllop.setVisible(false);
            jpnQlsv.setVisible(false);
            jpnQldiem.setVisible(true);
            
            state_add_diem = -1;
            jpnUpdateDiem.setVisible(false);
        }
    }//GEN-LAST:event_MenuMouseClick

    private void MenuMouseEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseEnter
        if(evt.getSource() == jpn1){
            jpn1.setBackground(new Color(240, 240, 240));
        }
        if(evt.getSource() == jpn2){
            jpn2.setBackground(new Color(240, 240, 240));
        }
        if(evt.getSource() == jpn3){
            jpn3.setBackground(new Color(240, 240, 240));
        }
    }//GEN-LAST:event_MenuMouseEnter

    private void MenuMouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseExit
        if(evt.getSource() == jpn1){
            jpn1.setBackground(new Color(255, 255, 255));
        }
        if(evt.getSource() == jpn2){
            jpn2.setBackground(new Color(255, 255, 255));
        }
        if(evt.getSource() == jpn3){
            jpn3.setBackground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_MenuMouseExit

    private void SearchSvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchSvMouseClicked
        clicked_search_LOP = 0;
        ArrayList<Sinhvien> sinhvienList = sinhvienList();
        jTableSv.setModel(new DefaultTableModel(null, new String[]{"MASV","HỌ TÊN","NGÀY SINH","ĐỊA CHỈ","TÊN LOGIN","MẬT KHẨU"}));
        DefaultTableModel model = (DefaultTableModel)jTableSv.getModel();
        Object[] row = new Object[6];
        for(int i=0;i<sinhvienList.size();i++){
            row[0] = sinhvienList.get(i).getMasv();
            row[1] = sinhvienList.get(i).getHoten();
            row[2] = sinhvienList.get(i).getNgaysinh();
            row[3] = sinhvienList.get(i).getDiachi();
            row[4] = sinhvienList.get(i).getTenDnSv();
            row[5] = sinhvienList.get(i).getMatkhau();
            model.addRow(row);
        }
        if(sinhvienList.size()<=0) jpnUpdateSv.setVisible(false);
        if(sinhvienList.size()>0) clicked_search_LOP = 1;
    }//GEN-LAST:event_SearchSvMouseClicked

    private void SearchDiemMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchDiemMouseClick
        clicked_search_DIEM = 0;
        ArrayList<Diem> diemList = diemList();
        jTableDiem.setModel(new DefaultTableModel(null, new String[]{"MÃ HỌC PHẦN","TÊN HỌC PHẦN","ĐIỂM"}));
        DefaultTableModel model = (DefaultTableModel)jTableDiem.getModel();
        Object[] row = new Object[3];
        for(int i=0;i<diemList.size();i++){
            row[0] = diemList.get(i).getMahp();
            row[1] = diemList.get(i).getTenhp();
            row[2] = diemList.get(i).getDiemthi();
            model.addRow(row);
        }
        if(diemList.size()<=0) jpnUpdateDiem.setVisible(false);
        if(diemList.size()>0) clicked_search_DIEM = 1;
    }//GEN-LAST:event_SearchDiemMouseClick

    private void AddSvMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddSvMouseClick
        if(txtSearchLopSv.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng Mã Lớp hoặc Tên Lớp vào ô Tim Kiếm và tìm kiếm trước tiên!");
        }else{
            SearchSvMouseClicked(evt);
            if(clicked_search_LOP == 1){
                state_add_sv++;
                if(state_add_sv%2==0){
                    jpnUpdateSv.setVisible(true);
                }else{
                    jpnUpdateSv.setVisible(false);
                } 
            }else{
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng Mã Lớp hoặc Tên Lớp vào ô Tim Kiếm!");
            }
        }
                       
    }//GEN-LAST:event_AddSvMouseClick

    private void AddDiemMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddDiemMouseClick
        if(txtSearchMasv.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng Mã Sinh Viên vào ô Tim Kiếm và tìm kiếm trước tiên!");
        }else{
            SearchDiemMouseClick(evt);
            if(clicked_search_DIEM == 1){
                state_add_diem++;
                if(state_add_diem%2==0){
                    jpnUpdateDiem.setVisible(true);
                    loadHocPhan();
                }else{
                    jpnUpdateDiem.setVisible(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng Mã Sinh Viên vào ô Tim Kiếm!");
            }
        }               
    }//GEN-LAST:event_AddDiemMouseClick

    private void StopSavingSv(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StopSavingSv
        jpnUpdateSv.setVisible(false);
        state_add_sv = -1;
    }//GEN-LAST:event_StopSavingSv

    private void StopSavingDiem(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StopSavingDiem
        jpnUpdateDiem.setVisible(false);
        state_add_diem = -1;
    }//GEN-LAST:event_StopSavingDiem

    private void SaveNewSvMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveNewSvMouseClick
        if(validateInput(1) == false){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin SINH VIÊN!");
        }else{
//            String sql = "";
//            
//            try{
//                
//            }catch(SQLException e){
//                System.out.println(e.getMessage());
//            }
        }
    }//GEN-LAST:event_SaveNewSvMouseClick

    private void SaveDiemMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveDiemMouseClick
        if(validateInput(2) == false){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin ĐIỂM!");
        }else{
            String sql = "EXEC SP_INS_BANGDIEM '" + txtSearchMasv.getText() + "','" + cbxDsHocphan.getSelectedItem().toString() + "','" + txtDiemHocPhan.getText() + "'";
            try{
                ps = cn.prepareStatement(sql);
                rs = ps.executeQuery();
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_SaveDiemMouseClick
    
    public ArrayList<Lop> lopList(){
        ArrayList<Lop> lopList = new ArrayList<>();
        String sql = "SELECT LP.MALOP, LP.TENLOP, NV.HOTEN, (SELECT COUNT(MALOP) FROM SINHVIEN SV) AS SLSV"
                    + " FROM NHANVIEN NV, LOP LP" + " WHERE NV.MANV = LP.MANV";
        
        try{
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();
            Lop lop;
            while(rs.next()){
                lop = new Lop(rs.getString("MALOP"), rs.getString("TENLOP"), rs.getString("HOTEN"), rs.getInt("SLSV"));
                lopList.add(lop);
            }
        }catch(SQLException e){
            System.out.println("Loi table LOP");
            System.out.println(e.getMessage());
        }
        return lopList;
    }
    
    public void showLopList(){
        ArrayList<Lop> lopList = lopList();
        DefaultTableModel model = (DefaultTableModel)jTableLop.getModel();
        Object[] row = new Object[4];
        for(int i=0;i<lopList.size();i++){
            row[0] = lopList.get(i).getMalop();
            row[1] = lopList.get(i).getTenlop();
            row[2] = lopList.get(i).getTennv();
            row[3] = lopList.get(i).getSlsv();
            model.addRow(row);
        }
    }
    
    public ArrayList<Sinhvien> sinhvienList(){
        ArrayList<Sinhvien> sinhvienList = new ArrayList<>();
        String sql = "SELECT SV.MASV, SV.HOTEN, SV.NGAYSINH, SV.DIACHI, SV.TENDN, SV.MATKHAU "
                    + "FROM SINHVIEN SV, LOP LP "
                    + "WHERE SV.MALOP = LP.MALOP AND (SV.MALOP = '" + txtSearchLopSv.getText() + "' OR LP.TENLOP = '" + txtSearchLopSv.getText() + "')";
        
        try{
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();
            Sinhvien sv;
            while(rs.next()){
                sv = new Sinhvien(rs.getString("MASV"), rs.getString("HOTEN"), rs.getString("NGAYSINH"), rs.getString("DIACHI"), rs.getString("TENDN"), rs.getString("MATKHAU"));
                sinhvienList.add(sv);
            }
        }catch(SQLException e){
            System.out.println("Loi table SINHVIEN");
            System.out.println(e.getMessage());
        }
        return sinhvienList;
    }
    
    public ArrayList<Diem> diemList(){
        ArrayList<Diem> diemList = new ArrayList<>();
        String sql = "EXEC SP_SEL_BANGDIEM '" + txtSearchMasv.getText() + "'";
        
        try{
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();
            Diem diem;
            while(rs.next()){
                diem = new Diem(rs.getString("MAHP"), rs.getString("TENHP"), rs.getFloat("DIEMTHI"));
                diemList.add(diem);
            }
        }catch(SQLException e){
            System.out.println("Loi table DIEM");
            System.out.println(e.getMessage());
        }
        return diemList;
    }
    
    public void loadHocPhan(){
        cbxDsHocphan.removeAllItems();
        String sql = "SELECT TENHP FROM HOCPHAN";
        try{
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next()){
                cbxDsHocphan.addItem(rs.getString("TENHP"));
            }
        }catch(SQLException e){
            System.out.println("Loi load HOCPHAN vao Combobox");
            System.out.println(e.getMessage());
        }
    }
    
    public boolean validateInput(int key){
        if(key == 1){
            if(txtNewMasv.getText().equals("") || txtNewName.getText().equals("") || jdcNewBirth.getDate().equals("") ||
                txtNewAddress.getText().equals("") || txtNewMalop.getText().equals("") || txtNewUsn.getText().equals("") || txtNewPass.getText().equals("")){
                return false;
            }
        }
        if(key == 2){
            if(cbxDsHocphan.getSelectedItem().equals("") || txtDiemHocPhan.getText().equals("")){
                return false;
            }
        }
        return true;
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxDsHocphan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDiem;
    private javax.swing.JTable jTableLop;
    private javax.swing.JTable jTableSv;
    private com.toedter.calendar.JDateChooser jdcNewBirth;
    private javax.swing.JPanel jpn1;
    private javax.swing.JPanel jpn2;
    private javax.swing.JPanel jpn3;
    private javax.swing.JPanel jpnCenter;
    private javax.swing.JPanel jpnHeader;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnQldiem;
    private javax.swing.JPanel jpnQllop;
    private javax.swing.JPanel jpnQlsv;
    private javax.swing.JPanel jpnSearchDiem;
    private javax.swing.JPanel jpnSearchLop;
    private javax.swing.JPanel jpnSearchSv;
    private javax.swing.JPanel jpnTableDiem;
    private javax.swing.JPanel jpnTableLop;
    private javax.swing.JPanel jpnTableSv;
    private javax.swing.JPanel jpnUpdateDiem;
    private javax.swing.JPanel jpnUpdateSv;
    private javax.swing.JPanel jpnUser;
    private javax.swing.JToggleButton jtbAddDiem;
    private javax.swing.JToggleButton jtbAddSv;
    private javax.swing.JToggleButton jtbDelDiem;
    private javax.swing.JToggleButton jtbDelSv;
    private javax.swing.JToggleButton jtbEditDiem;
    private javax.swing.JToggleButton jtbEditSv;
    private javax.swing.JToggleButton jtbSaveDiem;
    private javax.swing.JToggleButton jtbSaveSv;
    private javax.swing.JToggleButton jtbSearchDiem;
    private javax.swing.JToggleButton jtbSearchLop;
    private javax.swing.JToggleButton jtbSearchSv;
    private javax.swing.JToggleButton jtbStopSavingDiem;
    private javax.swing.JToggleButton jtbStopUpdatingSv;
    private javax.swing.JTextField txtDiemHocPhan;
    private javax.swing.JTextField txtNewAddress;
    private javax.swing.JTextField txtNewMalop;
    private javax.swing.JTextField txtNewMasv;
    private javax.swing.JTextField txtNewName;
    private javax.swing.JTextField txtNewPass;
    private javax.swing.JTextField txtNewUsn;
    private javax.swing.JTextField txtSearchLop;
    private javax.swing.JTextField txtSearchLopSv;
    private javax.swing.JTextField txtSearchMasv;
    // End of variables declaration//GEN-END:variables
}
