/*---------------------------------------------------------- 
MASV:	N17DCAT015
HO TEN CAC THANH VIEN:	- DOAN HONG DANG
						- NGUYEN DOAN HONG HANH
						- VO PHI HUNG
LAB:	03 - NHOM
NGAY:	19/9/2020
----------------------------------------------------------*/ 
CREATE TABLE SINHVIEN (
	MASV NVARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200), 
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(256) NOT NULL
)