/*---------------------------------------------------------- 
MASV:	N17DCAT015
HO TEN CAC THANH VIEN:	- DOAN HONG DANG
						- NGUYEN DOAN HONG HANH
						- VO PHI HUNG
LAB:	03 - NHOM
NGAY:	19/9/2020
----------------------------------------------------------*/ 
CREATE TABLE NHANVIEN (
	MANV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20), 
	LUONG VARBINARY(100),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(256) NOT NULL,
	PUBLICKEY VARCHAR(20) NOT NULL
)