CREATE PROC SP_SEL_PUBLIC_NHANVIEN (@MANV VARCHAR(256) ,@MK NVARCHAR(128)  )
AS 
BEGIN
SELECT NV.MANV, NV.HOTEN, NV.EMAIL, NV.TENDN,
CONVERT (VARCHAR(256),DECRYPTBYASYMKEY(ASYMKEY_ID(@MANV),CONVERT (VARCHAR(256),NV.LUONG),@MK)) AS LUONG,
NV.PUBKEY
FROM NHANVIEN NV
WHERE NV.MANV =  @MANV
END